# SPDX-FileCopyrightText: 2026 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

"""added quiz languages

Revision ID: a3f8c1d2e4b5
Revises: 9d7fa2e6b24c
Create Date: 2026-08-14 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
import ormar

# revision identifiers, used by Alembic.
revision = "a3f8c1d2e4b5"
down_revision = "9d7fa2e6b24c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quiz", sa.Column("languages", sa.JSON(), nullable=True))
    op.add_column("quiz", sa.Column("original_language", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz", "original_language")
    op.drop_column("quiz", "languages")
    # ### end Alembic commands ###
